CREATE TYPE [exch].[cme_future_position_limit_table_type] AS TABLE (
    [run_id]                                                               BIGINT        NOT NULL,
    [create_date]                                                          DATETIME      NOT NULL,
    [create_user]                                                          VARCHAR (50)  NOT NULL,
    [last_update_date]                                                     DATETIME      NOT NULL,
    [last_update_user]                                                     VARCHAR (50)  NOT NULL,
    [contract_name]                                                        VARCHAR (1024) NOT NULL,
    [rule_chapter]                                                         VARCHAR (1024) NULL,
    [commodity_code]                                                       VARCHAR (1024) NULL,
    [contract_size]                                                        VARCHAR (1024) NULL,
    [contract_units]                                                       VARCHAR (1024) NULL,
    [contract_type]                                                        VARCHAR (1024) NULL,
    [settlement]                                                           VARCHAR (1024) NULL,
    [contract_group]                                                       VARCHAR (1024) NULL,
    [diminishing_balance_contract]                                         VARCHAR (1024) NULL,
    [reporting_level]                                                      VARCHAR (1024) NULL,
    [spot_month_position_comprised_of_futures_and_deliveries]              VARCHAR (1024) NULL,
    [spot_month_aggregate_into_futures_equivalent_leg_1]                   VARCHAR (1024) NULL,
    [spot_month_aggregate_into_futures_equivalent_leg_2]                   VARCHAR (1024) NULL,
    [spot_month_aggregate_into_ratio_leg_1]                                VARCHAR (1024) NULL,
    [spot_month_aggregate_into_ratio_leg_2]                                VARCHAR (1024) NULL,
    [spot_Month_Accountability_Level]                                      VARCHAR (1024) NULL,
    [daily_accountability_level_for_daily_contract]                        VARCHAR (1024) NULL,
    [initial_spot_month_limit_in_net_futures_equivalents_leg_1_over_leg_2] VARCHAR (1024) NULL,
    [initial_spot_month_limit_effective_date]                              VARCHAR (1024) NULL,
    [spot_month_limit_in_contract_units_leg_1_over_leg_2]                  VARCHAR (1024) NULL,
    [subsequent_spot_month_limits_in_net_futures_equivalents]              VARCHAR (1024) NULL,
    [subsequent_spot_month_limits_effective_dates]                         VARCHAR (1024) NULL,
    [single_month_aggregate_into_futures_equivalent_leg_1]                 VARCHAR (1024) NULL,
    [single_month_aggregate_into_futures_equivalent_leg_2]                 VARCHAR (1024) NULL,
    [single_month_aggregate_into_ratio_leg_1]                              VARCHAR (1024) NULL,
    [single_month_aggregate_into_ratio_leg_2]                              VARCHAR (1024) NULL,
    [single_month_accountability_level_leg_1_over_leg_2]                   VARCHAR (1024) NULL,
    [single_month_limit_in_net_futures_equivalents_leg_1_over_leg_2]       VARCHAR (1024) NULL,
    [all_month_aggregate_into_futures_equivalent_leg_1]                    VARCHAR (1024) NULL,
    [all_month_aggregate_into_futures_equivalent_leg_2]                    VARCHAR (1024) NULL,
    [all_month_aggregate_into_ratio_leg_1]                                 VARCHAR (1024) NULL,
    [all_month_aggregate_into_ratio_leg_2]                                 VARCHAR (1024) NULL,
    [all_month_accountability_level_leg_1_over_leg_2]                      VARCHAR (1024) NULL,
    [all_month_limit_in_net_futures_equivalents_leg_1_over_leg_2]          VARCHAR (1024) NULL);

